# render.yaml - Instruções para o Render implantar nosso projeto

services:
  # Serviço para o Frontend (o site estático)
  - type: web
    name: gerador-carteirinha-frontend
    env: static
    # Diz ao Render para servir os arquivos da pasta 'frontend'
    staticPublishPath: ./frontend
    # Adiciona uma regra para que o site seja acessível
    routes:
      - type: rewrite
        source: /
        destination: /index.html

  # Serviço para o Backend (o servidor Node.js)
  - type: web
    name: gerador-carteirinha-backend
    env: node
    # Diz ao Render para procurar o código na pasta 'backend'
    rootDir: ./backend
    # Comandos para construir e iniciar o servidor
    buildCommand: "npm install"
    startCommand: "node server.js"
    # Configuração das variáveis de ambiente
    envVars:
      - key: PAGSEGURO_TOKEN
        # Este valor será inserido no painel do Render
        value: SEU_TOKEN_SECRETO_DO_PAGSEGURO_VAI_AQUI
      - key: NODE_VERSION
        value: 18 # Usa uma versão estável do Node.js
